url=https://app.joinditto.in/fq
browser=chrome
CoverAmount=\u20B950 L
Date_of_Birth=06/02/1994
Pincode=560037
AnnualIncome=10,00,000
MonthlyExpenses=10,000
Education=Post Graduate
sumAssured=5000000
ratePerLaks184=184.8
ratePerLaks209=209.78